name: Python application

on:
  push:
    branches: [ "Master" ]
  pull_request:
    branches: [ "Master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install OpenJDK
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
    - name: Set up JAVA_HOME
      run: echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
    - name: Install Build Tools
      run: |
        sudo apt-get install -y build-essential
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install Cython
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
